### ISSUE TITLE
Error al ejecutar comando isis2json.py

### ISSUE THREAD

**Issue by victorricardo** [bireme/isis2json#1]
Cuando ejecuto:

root@victor-desktop:/srv/bireme-isis2json# ./isis2json.py artigo.iso -c -i 2 -q 100 | curl -d @-   -X POST http://127.0.0.1:5984/scielo/_bulk_docs   -H"Content-Type: application/json"

Se visualiza el sgte error:

Traceback (most recent call last):
  File "./isis2json.py", line 240, in <module>
    args.id, args.uuid, args.mongo, args.mfn, args.type, args.prefix, args.constant)
  File "./isis2json.py", line 134, in writeJsonArray
    raise KeyError(msg % (id_tag, i))
KeyError: 'id tag #2 not found in record 0'
{"error":"bad_request","reason":"invalid UTF-8 JSON"}

**Comment by renatomurasaki** [comment]
This repository has been archived. It is now read-only.
