### ISSUE TITLE
No module name jyson

### ISSUE THREAD

**Issue by barraponto** [bireme/isis2json#3]
When trying to process a .mst file, I found the following error:

```
Traceback (most recent call last):
  File "./isis2json.py", line 33, in <module>
    from com.xhaus.jyson import JysonCodec as json
ImportError: No module named jyson
```

Of course, the jyson jar is still in the lib folder. Running Jython 2.5 under Arch Linux.

**Comment by delfuria** [comment]
Hi, i running on a Win 8.1 machine and i have the same issue.
Is there any news ??

**Comment by renatomurasaki** [comment]
This repository has been archived. It is now read-only.
